status = error
name = GameLogging

appender.console.type = Console
appender.console.name = ConsoleAppender
appender.console.target = SYSTEM_OUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{EEE yyyy-MM-dd HH:mm:ss.SSS} %-5level [%t] %c.%M:%L - %msg%n

appender.file.type = File
appender.file.name = FileAppender
appender.file.fileName = logs/game.log
appender.file.append = true
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = %d{EEE yyyy-MM-dd HH:mm:ss.SSS} %-5level [%t] %c.%M:%L - %msg%n

rootLogger.level = debug
rootLogger.appenderRefs = console, file
rootLogger.appenderRef.console.ref = ConsoleAppender
rootLogger.appenderRef.file.ref = FileAppender
